FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["portfolio.csproj", "./"]
RUN dotnet restore "portfolio.csproj"

COPY . .
RUN dotnet publish "portfolio.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "portfolio.dll"]
